// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function ExportBackup() {
  return window['go']['main']['App']['ExportBackup']();
}

export function ExportConversation(arg1, arg2) {
  return window['go']['main']['App']['ExportConversation'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetContextUsage() {
  return window['go']['main']['App']['GetContextUsage']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportBackup() {
  return window['go']['main']['App']['ImportBackup']();
}

export function ListConversations() {
  return window['go']['main']['App']['ListConversations']();
}

export function ListMCPServers() {
  return window['go']['main']['App']['ListMCPServers']();
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function ListTools() {
  return window['go']['main']['App']['ListTools']();
}

export function LoadConversation(arg1) {
  return window['go']['main']['App']['LoadConversation'](arg1);
}

export function NewConversation(arg1) {
  return window['go']['main']['App']['NewConversation'](arg1);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function ProbeMCPServer(arg1) {
  return window['go']['main']['App']['ProbeMCPServer'](arg1);
}

export function RenameConversation(arg1, arg2) {
  return window['go']['main']['App']['RenameConversation'](arg1, arg2);
}

export function RespondPermission(arg1) {
  return window['go']['main']['App']['RespondPermission'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveMCPServers(arg1) {
  return window['go']['main']['App']['SaveMCPServers'](arg1);
}

export function SearchConversations(arg1) {
  return window['go']['main']['App']['SearchConversations'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetConversationModel(arg1) {
  return window['go']['main']['App']['SetConversationModel'](arg1);
}

export function StartRecording() {
  return window['go']['main']['App']['StartRecording']();
}

export function StopAgent() {
  return window['go']['main']['App']['StopAgent']();
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}

export function TranscribeAudio(arg1) {
  return window['go']['main']['App']['TranscribeAudio'](arg1);
}

export function UpdateConversationPath(arg1) {
  return window['go']['main']['App']['UpdateConversationPath'](arg1);
}

export function WhisperAvailable() {
  return window['go']['main']['App']['WhisperAvailable']();
}
