// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';
import {app} from '../models';
import {history} from '../models';

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function DeleteConversation(arg1:string):Promise<void>;

export function ExportBackup():Promise<string>;

export function ExportConversation(arg1:string,arg2:string):Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetContextUsage():Promise<app.ContextUsage>;

export function GetVersion():Promise<string>;

export function ImportBackup():Promise<string>;

export function ListConversations():Promise<Array<history.ConvMeta>>;

export function ListMCPServers():Promise<Array<config.MCPServerConfig>>;

export function ListModels():Promise<main.ModelList>;

export function ListTools():Promise<Array<main.ToolInfo>>;

export function LoadConversation(arg1:string):Promise<history.Conversation>;

export function NewConversation(arg1:string):Promise<history.Conversation>;

export function PickDirectory():Promise<string>;

export function ProbeMCPServer(arg1:config.MCPServerConfig):Promise<Array<string>>;

export function RenameConversation(arg1:string,arg2:string):Promise<void>;

export function RespondPermission(arg1:boolean):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<string>;

export function SaveMCPServers(arg1:Array<config.MCPServerConfig>):Promise<string>;

export function SearchConversations(arg1:string):Promise<Array<history.ConvMeta>>;

export function SendMessage(arg1:string):Promise<main.ChatResponse>;

export function SetConversationModel(arg1:string):Promise<void>;

export function StartRecording():Promise<void>;

export function StopAgent():Promise<void>;

export function StopRecording():Promise<string>;

export function TranscribeAudio(arg1:Array<number>):Promise<string>;

export function UpdateConversationPath(arg1:string):Promise<void>;

export function WhisperAvailable():Promise<boolean>;
